/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminMenu: typeof import('./components/admin/AdminMenu.vue')['default']
    Avatar: typeof import('./components/user/Avatar.vue')['default']
    AvatarInfo: typeof import('./components/user/AvatarInfo.vue')['default']
    CodeEditor: typeof import('./components/judge/CodeEditor.vue')['default']
    CodeRun: typeof import('./components/judge/CodeRun.vue')['default']
    DataMake: typeof import('./components/dakemake/DataMake.vue')['default']
    DataMakeRow: typeof import('./components/dakemake/DataMakeRow.vue')['default']
    DataMakeValue: typeof import('./components/dakemake/DataMakeValue.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    HeaderNav: typeof import('./components/HeaderNav.vue')['default']
    LanguageSelect: typeof import('./components/judge/LanguageSelect.vue')['default']
    LogoutButton: typeof import('./components/user/LogoutButton.vue')['default']
    ProblemDifficultySelect: typeof import('./components/problem/ProblemDifficultySelect.vue')['default']
    ProblemList: typeof import('./components/problem/ProblemList.vue')['default']
    ProblemListItem: typeof import('./components/problem/ProblemListItem.vue')['default']
    Problems: typeof import('./components/problem/Problems.vue')['default']
    ProblemSelect: typeof import('./components/problem/ProblemSelect.vue')['default']
    ProblemTagSelect: typeof import('./components/problem/ProblemTagSelect.vue')['default']
    RecordInfo: typeof import('./components/record/RecordInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCaseEdit: typeof import('./components/problem/TestCaseEdit.vue')['default']
    TestTable: typeof import('./components/problem/TestTable.vue')['default']
    ToUserSettingButton: typeof import('./components/user/ToUserSettingButton.vue')['default']
  }
}
