/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminMenu: typeof import('./components/admin/AdminMenu.vue')['default']
    Avatar: typeof import('./components/user/Avatar.vue')['default']
    AvatarInfo: typeof import('./components/user/AvatarInfo.vue')['default']
    CodeEditor: typeof import('./components/CodeEditor.vue')['default']
    CodeRun: typeof import('./components/CodeRun.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    HeaderNav: typeof import('./components/HeaderNav.vue')['default']
    LanguageSelect: typeof import('./components/LanguageSelect.vue')['default']
    LogoutButton: typeof import('./components/auth/LogoutButton.vue')['default']
    ProblemDifficultySelect: typeof import('./components/problem/ProblemDifficultySelect.vue')['default']
    ProblemList: typeof import('./components/problem/ProblemList.vue')['default']
    ProblemListItem: typeof import('./components/problem/ProblemListItem.vue')['default']
    Problems: typeof import('./components/problem/Problems.vue')['default']
    ProblemSelect: typeof import('./components/problem/ProblemSelect.vue')['default']
    ProblemTagSelect: typeof import('./components/problem/ProblemTagSelect.vue')['default']
    RecordInfo: typeof import('./components/RecordInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToUserSettingButton: typeof import('./components/user/ToUserSettingButton.vue')['default']
  }
}
